### PR TITLE
Update config.xml

### PR DESCRIPTION
**Pull request by cgadgetz**

### CODE REVIEW

**Comment by kicker10BOG** [comment]
Please download the files and put them on a server you have access to before making changes. Do not include the github stuff when you upload the files to your server.

**Comment by cgadgetz** [comment]
Thanks. I replied to your post on daddyleagues. Sorry for not really understanding how this works. I'm researching now to try to figure this out. As far as server I uploaded it to my onedrive account but it's not working. I'm assuming I need to upload it to another type of place. If you have time can you push me in the right direction please. Appreciate your help.

**Comment by kicker10BOG** [comment]
No problem. 

You need some kind of web server. GoDaddy is a popular one web host. There may be less expensive options if all you want to do is host the bot. You could search for free ones, but I'm not sure any of those would work well enough. I'll let you know if I decide to start hosting bots on the server I use too.

**Comment by cgadgetz** [comment]
I don't mind playing for web hosting. Thanks for taking the time to get back to me. Once I have that is it as simple as uploading the files there? Also I'm considering switching to discord would the web hosting by goDaddy still be be beneficial?

**Comment by kicker10BOG** [comment]
Yeah, just upload the files and put the link to the bot files ([your url]/adminBot.php for the bot with admin functions and [your url]/mainBot.php for the bot without admin functions) in the bot you create at https://dev.groupme.com/bots ... Hopefully the instructions on the readme will be enough from here, but let me know if you need more help. 

This bot currently isn't ready for Discord, but I have one in the works. Also, Discord bots work differently from groupme bots and you can actually run it straight from your home pc, but you have to make sure it always stays on. If you want to host it on a server, it needs to be more than a web server (cheapest option is probably VPS). But that bot isn't ready yet. I've been busy with my last semester of grad school. lol.

**Comment by cgadgetz** [comment]
Sorry to bother you again. I purchased web hosting and a domain from godaddy. I'm not sure exactly where I would upload the files. I found a upload option but after uploaded them I do not see a way to pull the url so obviously i'm in the wrong place. Where should I upload the files to?

**Comment by cgadgetz** [comment]
I also sent you a small donation to your paypal for dealing with my questions lol and the work you've done to get create this bot

**Comment by kicker10BOG** [comment]
You probably registered a domain name when you purchased hosting. Try putting that in the browser's address bar.

**Comment by kicker10BOG** [comment]
Let me know what comes up. 

You could also try [yourdomain]/mainBot.php and you should get just a blank page. .. perhaps I should add a line of output to it.

**Comment by cgadgetz** [comment]
404 error page can not be displayed

**Comment by kicker10BOG** [comment]
create a file called "index.php" and put this in it

```
<?php
$dir    = './';
$files = scandir($dir);
foreach ($files as $key => $f) {
	print("<a href='$f'>$f</a><br>");
}
?>
```

then upload it to the root directory (probably where you uploaded the bot folder) and go to your url again. It should list all files and folders there.

**Pull request closed without merging**
